#!/bin/bash
# Author : Caleb Theil 
# Github page : https://github.com/ctheil
#####################################################
# Tested on : Debian (RaspberryPi OS (with desktop))
# Updated version : v1.0 (Updated on June-2024)
#####################################################
# Purpose : Sorce the config, schedule the power on cycle, and shutdown the device
# NOTE: This script must be executed bu a super-user (su or sudo)

LOGFILE="/opt/kiosk/db/shutdown.log"
CONFIG_FILE="/opt/kiosk/db/config.txt"
source $CONFIG_FILE

echo "--- --- ---" >> $LOGFILE
echo "Script started at: $(date)" >> $LOGFILE

WAKEUP_TIME_UTC=$(date +%s -d "$weekend_wakeup" -u)

#schedule wakeup
sudo rtcwake -m no -t $WAKEUP_TIME_UTC >> $LOGFILE 2>&1

echo "rtcwake command issued" >> $LOGFILE
echo "rtc wake command issued for $weekend_wakeup ($WAKEUP_TIME_UTC)

**********************************
   Shutting down in 10 seconds
**********************************
"

sleep 10

sudo /sbin/shutdown -h now >> $LOGFILE 2>&1

echo "Shutdown command issued at: $(date)" >> $LOGFILE
